#!/usr/bin/env node
/**
 * Syncs with shadcn/ui's new-york-v4 registry:
 *
 *   upstream/ui/*.tsx, upstream/hooks/*.ts   the web sources each component is ported from
 *   upstream/docs/*.mdx                      shadcn's docs page for each component (title, description, usage)
 *   upstream/COMMIT                          the shadcn commit they come from
 *   src/generated/themes.ts                  base colors and theme colors, as CSS variables
 *
 * Diff `upstream/` after a sync to see which components changed upstream.
 *
 * Usage:
 *   node scripts/sync-shadcn.mjs                   # sparse-clones shadcn-ui/ui into .shadcn/
 *   SHADCN_SRC=/path/to/ui node scripts/sync-shadcn.mjs
 *   SHADCN_REF=<sha|branch> node scripts/sync-shadcn.mjs
 */
import { execSync } from "node:child_process"
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const SPARSE = [
  "apps/v4/registry/new-york-v4/ui",
  "apps/v4/registry/new-york-v4/hooks",
  "apps/v4/registry/themes.ts",
  "apps/v4/content/docs/components/radix",
]

function checkout() {
  if (process.env.SHADCN_SRC) return path.resolve(process.env.SHADCN_SRC)
  const dir = path.join(root, ".shadcn")
  if (!fs.existsSync(dir)) {
    execSync(`git clone --depth 1 --filter=blob:none --sparse https://github.com/shadcn-ui/ui.git "${dir}"`, {
      stdio: "inherit",
    })
  }
  execSync(`git -C "${dir}" sparse-checkout set --no-cone ${SPARSE.map((s) => `/${s}`).join(" ")}`, {
    stdio: "inherit",
  })
  if (process.env.SHADCN_REF) {
    execSync(`git -C "${dir}" fetch --depth 1 origin ${process.env.SHADCN_REF}`, { stdio: "inherit" })
    execSync(`git -C "${dir}" checkout FETCH_HEAD`, { stdio: "inherit" })
  }
  return dir
}

const src = checkout()
const registry = path.join(src, "apps/v4/registry")
let commit = "unknown"
try {
  commit = execSync(`git -C "${src}" rev-parse HEAD`).toString().trim()
} catch {}

// Upstream sources
for (const [from, to] of [
  ["registry/new-york-v4/ui", "upstream/ui"],
  ["registry/new-york-v4/hooks", "upstream/hooks"],
  ["content/docs/components/radix", "upstream/docs"],
]) {
  const out = path.join(root, to)
  fs.rmSync(out, { recursive: true, force: true })
  fs.mkdirSync(out, { recursive: true })
  for (const f of fs.readdirSync(path.join(src, "apps/v4", from))) {
    if (f.startsWith("_")) continue
    fs.copyFileSync(path.join(src, "apps/v4", from, f), path.join(out, f))
  }
}
fs.writeFileSync(path.join(root, "upstream/COMMIT"), `${commit}\n`)

// Themes: registry/themes.ts is a TypeScript array literal; strip the types and evaluate it.
const themesTs = fs.readFileSync(path.join(registry, "themes.ts"), "utf8")
const js = themesTs
  .replace(/^import .*$/gm, "")
  .replace(/export const THEMES: [^=]+=/, "export const THEMES =")
  .replace(/\] as const satisfies [^\n]+/, "]")
  .replace(/^export type .*$/gm, "")
const { THEMES } = await import(`data:text/javascript;base64,${Buffer.from(js).toString("base64")}`)

// Full themes (every token) are base colors; the rest are theme colors layered on top.
const baseColors = {}
const themeColors = {}
for (const t of THEMES) {
  const entry = { light: t.cssVars.light ?? {}, dark: t.cssVars.dark ?? {} }
  if ("background" in entry.light) baseColors[t.name] = entry
  else themeColors[t.name] = entry
}

const header = `// Generated by scripts/sync-shadcn.mjs from shadcn/ui ${commit.slice(0, 12)}. Do not edit.\n\n`
const body =
  `export const baseColors = ${JSON.stringify(baseColors, null, 2)} as const\n\n` +
  `export const themeColors = ${JSON.stringify(themeColors, null, 2)} as const\n\n` +
  `export type BaseColor = keyof typeof baseColors\n` +
  `export type ThemeColor = keyof typeof themeColors\n` +
  `export const SHADCN_COMMIT = ${JSON.stringify(commit)}\n`
fs.mkdirSync(path.join(root, "src/generated"), { recursive: true })
fs.writeFileSync(path.join(root, "src/generated/themes.ts"), header + body)

console.log(
  `Synced shadcn ${commit.slice(0, 12)}: ${Object.keys(baseColors).length} base colors, ` +
    `${Object.keys(themeColors).length} theme colors.`
)
